const beats = [{
    "kana": "クラークさんの国はアメリカで、",
    "speaker": "narrator",
    "phrase": 6,
}, {
    "kana": "今、西かいがんのシアトルに住んでいますが、",
    "speaker": "narrator",
    "phrase": 7,
}, {
    "kana": "よく会ぎで東京に出ちょうします。",
    "speaker": "narrator",
    "phrase": 8
}, {
    "kana": "今度は休みをとって、",
    "speaker": "narrator",
    "phrase": 9
}, {
    "kana": "九州か北海道に旅行したいんですが、",
    "speaker": "narrator",
    "phrase": 10
}, {
    "kana": "よくわかりません。",
    "speaker": "narrator",
    "phrase": 11
}, {
    "kana": "それで、",
    "speaker": "narrator",
    "phrase": 12
}, {
    "kana": "会社のひる休みにどうりょうの林さんにそうだんしました。",
    "speaker": "narrator",
    "phrase": 13
}, {
    "kana": "来月また東京で会ぎなんです。",
    "speaker": "クラーク",
    "phrase": 14
}, {
    "kana": "それで、その後ー週間ぐらい九州か北海道に旅行したいんです。",
    "speaker": "クラーク",
    "phrase": 15
}, {
    "kana": "それはいいかんがえですね。",
    "speaker": "林",
    "phrase": 16
}, {
    "kana": "クラークさんはいつも東京だけですからね。",
    "speaker": "林",
    "phrase": 17
}, {
    "kana": "ええ、そうなんですよ。",
    "speaker": "クラーク",
    "phrase": 18
}, {
    "kana": "林さん、",
    "speaker": "クラーク",
    "phrase": 19
}, {
    "kana": "九州と北海道とではどちらのほうがいいですか。",
    "speaker": "クラーク",
    "phrase": 20
}, {
    "kana": "そうですね。",
    "speaker": "林",
    "phrase": 21
}, {
    "kana": "今はもう北はさむいですよ。",
    "speaker": "林",
    "phrase": 22
}, {
    "kana": "北海道では多分雪が振っています。",
    "speaker": "林",
    "phrase": 23
}, {
    "kana": "南のほうが気候がいいですから、",
    "speaker": "林",
    "phrase": 24
}, {
    "kana": "九州のほうが北海道よりいいですよ。",
    "speaker": "林",
    "phrase": 25
}, {
    "kana": "九州には有名な火山があって、",
    "speaker": "林",
    "phrase": 26
}, {
    "kana": "温泉もたくさんあるんです。",
    "speaker": "林",
    "phrase": 27
}, {
    "kana": "それに美味しい食べ物もいろいろありますよ。",
    "speaker": "林",
    "phrase": 28
}, {
    "kana": "クラークさんはラーメンが好きでしたね。",
    "speaker": "林",
    "phrase": 30
}, {
    "kana": "九州はラーメンやチャンポンが有名ですよ。",
    "speaker": "林",
    "phrase": 31
}, {
    "kana": "それはいいですね。",
    "speaker": "クラーク",
    "phrase": 32
}, {
    "kana": "じゃあ、九州に行ってみます。",
    "speaker": "クラーク",
    "phrase": 33
}, {
    "kana": "東京から九州まで飛行機としんかんせんとでは",
    "speaker": "クラーク",
    "phrase": 34
}, {
    "kana": "どちらのほうが便利ですか。",
    "speaker": "クラーク",
    "phrase": 35
}, {
    "kana": "飛行機のほうがずっとはやいですが、",
    "speaker": "林",
    "phrase": 36
}, {
    "kana": "新幹線のほうが便利ですよ。",
    "speaker": "林",
    "phrase": 37
}, {
    "kana": "途中で新幹線を降りて、",
    "speaker": "林",
    "phrase": 39
}, {
    "kana": "いろいろな所によることができます。",
    "speaker": "林",
    "phrase": 40
}, {
    "kana": "そうですか。",
    "speaker": "クラーク",
    "phrase": 41
}, {
    "kana": "あまり時間がないんですけど、",
    "speaker": "クラーク",
    "phrase": 42
}, {
    "kana": "日本の古いお城も見てみたいんです。",
    "speaker": "クラーク",
    "phrase": 43
}, {
    "kana": "どこがいいですか。",
    "speaker": "クラーク",
    "phrase": 44
}, {
    "kana": "じゃあ、名古屋か大阪か姫路のお城ですね。",
    "speaker": "林",
    "phrase": 45
}, {
    "kana": "ぞの中でどれが一番有名ですか。",
    "speaker": "クラーク",
    "phrase": 46
}, {
    "kana": "もちろん姫路が一番有名ですね。",
    "speaker": "林",
    "phrase": 47
}, {
    "kana": "姫路のお城は日本で一番綺麗いです。",
    "speaker": "林",
    "phrase": 48
}, {
    "kana": "そうですか。",
    "speaker": "クラーク",
    "phrase": 49
}, {
    "kana": "ぜひ行ってみたいです。",
    "speaker": "クラーク",
    "phrase": 50
}];