const beats = [
    {
        "kana": "よしえさんとたけしさんは",
        "speaker": "narrator",
        "phrase": 4,
    }, {
        "kana": "朝のじゅぎょうがおわって、",
        "speaker": "narrator",
        "phrase": 5,
    }, {
        "kana": "これから二人で昼ごはんを食べに行きます。",
        "speaker": "narrator",
        "phrase": 6,
    }, {
        "kana": "たけし、",
        "speaker": "よしえ",
        "phrase": 8,
    }, {
        "kana": "お昼ご飯、一緒に食べない？",
        "speaker": "よしえ",
        "phrase": 9,
    }, {
        "kana": "うん、いいね。",
        "speaker": "たけし",
        "phrase": 10,
    }, {
        "kana": "あまり時間ないけど。",
        "speaker": "たけし",
        "phrase": 11,
    }, {
        "kana": "午後のクラスがあるから",
        "speaker": "たけし",
        "phrase": 12,
    }, {
        "kana": "じゃあ、何がいいかな。",
        "speaker": "よしえ",
        "phrase": 13,
    }, {
        "kana": "牛丼とハンバーガーとラーメンとどれが一番食べたい？",
        "speaker": "よしえ",
        "phrase": 15,
    }, {
        "kana": "牛丼が一番いいな。安くてボリュームがあるから。よっちゃんは？",
        "speaker": "たけし",
        "phrase": 16,
    }, {
        "kana": "私も牛丼がいい。",
        "speaker": "よしえ",
        "phrase": 17,
    }, {
        "kana": "どっちで食べる？",
        "speaker": "よしえ",
        "phrase": 18,
    }, {
        "kana": "駅前のとすぐそこの木村屋と。",
        "speaker": "よしえ",
        "phrase": 20,
    }, {
        "kana": "木村屋は駅前のほどおいしくないけど、",
        "speaker": "たけし",
        "phrase": 21,
    }, {
        "kana": "きっと混んでるから今日木村屋に行く？",
        "speaker": "たけし",
        "phrase": 22,
    }, {
        "kana": "うん、そうね。",
        "speaker": "よしえ",
        "phrase": 23,
    }
];